# Generated by Django 6.0.3 on 2026-04-19 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20)),
                ('country', models.CharField(blank=True, choices=[('ghana', 'Ghana'), ('nigeria', 'Nigeria'), ('kenya', 'Kenya'), ('south_africa', 'South Africa'), ('usa', 'United States'), ('uk', 'United Kingdom'), ('canada', 'Canada'), ('other', 'Other')], max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('football', 'Football'), ('basketball', 'Basketball'), ('music', 'Music'), ('dance', 'Dance'), ('acting', 'Acting'), ('other', 'Other')], max_length=50)),
                ('experience_level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('professional', 'Professional')], max_length=20)),
                ('height_cm', models.PositiveIntegerField(blank=True, null=True)),
                ('weight_kg', models.PositiveIntegerField(blank=True, null=True)),
                ('bio', models.TextField()),
                ('skills', models.TextField(blank=True, help_text='Example: Singing, Acting, Football')),
                ('achievements', models.TextField(blank=True, help_text='Awards, competitions, performances, etc.')),
                ('social_link', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='talent_images/')),
                ('video_link', models.URLField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TalentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='talent_gallery/')),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('talent_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='talent.talentprofile')),
            ],
        ),
    ]
