# Generated by Django 6.0.3 on 2026-03-31 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talentprofile',
            name='created_at',
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='talent_images/'),
        ),
    ]
