# Generated by Django 6.0.3 on 2026-04-07 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0002_remove_talentprofile_created_at_talentprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentprofile',
            name='video_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
