# Generated by Django 6.0.3 on 2026-04-07 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0003_talentprofile_video_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='talent_gallery/')),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('talent_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='talent.talentprofile')),
            ],
        ),
    ]
